<?php

use App\Exceptions\InvalidSosreportFilenameException;
use App\Models\User;
use App\Providers\VaultTools;
use Database\Seeders\RolesTableSeeder;

/*
 * VaultTools::parseFilename() decomposes a sos report archive name into
 * host/case/label/date/sosid by splitting on '-' and '.' and reading fixed
 * positions from the right. A filename edited after being generated by sos
 * report (segments inserted/removed) desyncs those positions and used to
 * produce a garbage date string that later crashed Carbon-backed table
 * columns on the upload and browse pages (see reported issue: a user renamed
 * "sosreport-test3-2024-05-23-svawtdh.tar.xz" to
 * "sosreport-test3-2024-05-23-svawtdh-n3.xlarge.tar.xz" by appending an
 * instance-type suffix, tripping a 500 on both pages).
 */

beforeEach(function () {
    $this->seed(RolesTableSeeder::class);
    $this->user = User::factory()->create();
});

it('parses valid current-format sos report filenames', function (string $filename, string $host, string $date, ?string $case, ?string $label) {
    $vtools = new VaultTools($this->user);

    $fdata = $vtools->parseFilename($filename);

    expect($fdata->host)->toBe($host);
    expect($fdata->date)->toBe($date);
    if ($case !== null) {
        expect($fdata->case)->toBe($case);
    }
    if ($label !== null) {
        expect($fdata->label)->toBe($label);
    }
})->with([
    'host + date + sosid only' => ['sosreport-host0-2024-09-21-nhnyjgp.tar.xz.gpg', 'host0', '2024-09-21', null, null],
    'host + case + date + sosid' => ['sosreport-host0-SSUP2026-2024-09-21-nhnyjgp.tar.xz.gpg', 'host0', '2024-09-21', 'SSUP2026', null],
    // sos report's --label option inserts an extra label segment ahead of the case id.
    // Note: the pre-existing label/case-id split concatenates both segments into
    // `case` (a quirk of the "difficult part" disambiguation below); not this fix's concern.
    'host + label + case + date + sosid' => ['sosreport-host0-rhel91-SSUP2026-2024-09-21-nhnyjgp.tar.xz.gpg', 'host0', '2024-09-21', 'rhel91-SSUP2026', 'rhel91'],
    'secured + host + case + date + sosid' => ['secured-sosreport-host0-SSUP2026-2024-09-21-nhnyjgp-obfuscated.tar.xz.gpg', 'host0', '2024-09-21', 'SSUP2026', null],
    'label with dashes' => ['secured-sosreport-host1-sar-ISS-7096-2025-04-14-epchzbr-obfuscated.tar.xz.gpg', 'host1', '2025-04-14', null, 'sar'],
]);

it('rejects a filename renamed after generation (the reported regression)', function () {
    $vtools = new VaultTools($this->user);

    $vtools->parseFilename('sosreport-test3-2024-05-23-svawtdh-n3.xlarge.tar.xz');
})->throws(InvalidSosreportFilenameException::class);

it('rejects filenames whose date segment is not a real calendar date', function (string $filename) {
    $vtools = new VaultTools($this->user);

    $vtools->parseFilename($filename);
})->with([
    'renamed with instance-type suffix' => ['sosreport-test3-2024-05-23-svawtdh-n3.xlarge.tar.xz'],
    'month out of range' => ['sosreport-host-2024-13-40-abcdef.tar.gz'],
    'non-numeric date parts' => ['sosreport-host-foo-bar-baz-abcdef.tar.gz'],
])->throws(InvalidSosreportFilenameException::class);
