<?php

namespace App\Exceptions;

use Exception;

/**
 * Thrown by VaultTools::parseFilename() when a filename passes the basic
 * "sosreport-...*" upload gate but its date/id segments cannot be reliably
 * decomposed (e.g. the file was renamed after being generated by sos report).
 */
class InvalidSosreportFilenameException extends Exception {}
