<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Schema;
use Sushi\Sushi;

class Tools extends Model
{
    use Sushi;

    public function getRows(): array
    {
        $data = [
            [
                'name' => 'sosBrowser',
                'id' => '1',
                'enabled' => true,
                'title' => 'sos Browser',
                'status' => 'available',
                'icon' => 'phosphor-tree-view-duotone',
                'url' => '',
                'image' => '/storage/pages/tools/sosBrowser.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open sos Report Browser Tab',
                'description' => 'The main sosreport browser tool that lets users explore system logs, configuration files, and collected diagnostics in a structured, easy-to-navigate interface.',
                'type' => 'basic',
            ],
            [
                'name' => 'sosViewer',
                'id' => '2',
                'enabled' => true,
                'title' => 'sos Viewer',
                'status' => 'available',
                'icon' => 'phosphor-binoculars-duotone',
                'url' => '',
                'image' => '/storage/pages/tools/sosViewer.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open File Tab',
                'description' => 'The main sosreport file viewer that opens individual files for reading, searching, annotating, sharing, and downloading, while displaying rich metadata such as date, size, line count, customer, and case details.',
                'type' => 'basic',
            ],
            [
                'name' => 'Summary',
                'id' => '10',
                'enabled' => true,
                'title' => 'Summary',
                'status' => 'available',
                'icon' => 'phosphor-stethoscope-duotone',
                'url' => '/sosTool/[vid]/[did]/Summary/[caseid]',
                'image' => '/storage/pages/tools/Summary.png',
                'showInMenu' => true,
                'showInLandingPage' => true,
                'tooltip' => 'Open Summary Tab',
                'description' => 'A simple, focused dashboard showing extended system data and subsystem status with quick drill-down access. Each dashboard component is a tool in itself.',
                'type' => 'basic',
            ],
            [
                'name' => 'Top',
                'id' => '20',
                'enabled' => true,
                'title' => 'Top',
                'status' => 'available',
                'icon' => 'phosphor-mountains-duotone',
                'url' => '/sosTool/[vid]/[did]/Top/[caseid]',
                'image' => '/storage/pages/tools/Top.png',
                'showInMenu' => true,
                'showInLandingPage' => true,
                'tooltip' => 'Open Top Tab',
                'description' => 'A system status dashboard for those who prefer the top command layout.',
                'type' => 'basic',
            ],
            [
                'name' => 'Report',
                'id' => '60',
                'enabled' => true,
                'title' => 'Report',
                'status' => 'available',
                'icon' => 'phosphor-list-checks-duotone',
                'url' => '/reports/[caseid]/?create=1',
                'image' => '/storage/pages/tools/Report.png',
                'showInMenu' => true,
                'showInLandingPage' => true,
                'tooltip' => 'Create a New Incident Report',
                'description' => 'A report editor that lets users create professional root cause analysis documents enriched with subsystem state data and export them as PDFs ready for attachment to any ticketing system.',
                'type' => 'advanced',
            ],
            [
                'name' => 'Compare',
                'id' => '120',
                'enabled' => true,
                'title' => 'Compare',
                'status' => 'available',
                'icon' => 'phosphor-git-diff-duotone',
                'url' => '/sosTool/[vid]/[did]/Compare/[caseid]',
                'image' => '/storage/pages/tools/Compare.png',
                'showInMenu' => true,
                'showInLandingPage' => true,
                'tooltip' => 'Open sos Report Compare Tab',
                'description' => 'A comparison tool that highlights differences between two sosreport directories, making it easy to spot subsystem state variations, and potential causes of system issues.',
                'type' => 'advanced',
            ],
            [
                'name' => 'fileCompare',
                'id' => '121',
                'enabled' => true,
                'title' => 'File Compare',
                'status' => 'available',
                'icon' => 'phosphor-git-diff-duotone',
                'url' => '/sosTool/[vid]/[did]/FileCompare/[caseid]/[fid]',
                'image' => '/storage/pages/tools/fileCompare.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Compare file with that of another case',
                'description' => 'A file comparison tool that highlights differences between two files form different sosreports, making it easy to identify configuration changes, and potential causes of system issues.',
                'type' => 'advanced',
            ],
            [
                'name' => 'Mil AI Assistant',
                'id' => '30',
                'enabled' => true,
                'title' => 'Mil AI Assistant',
                'status' => 'available',
                'icon' => 'phosphor-robot-duotone',
                'url' => '/mil',
                'image' => '/storage/pages/Carousel/carrousel09.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open AI Assistant',
                'description' => 'Mil helps on fast and accurate sosreport analysis, sos-vault, sos command  and Linux usage queries. (You need to provide your own OpenAI or Anthropic key for the AI Assistant for sosreport analysis.)',
                'type' => 'advanced',
            ],
            [
                'name' => 'Compliance',
                'id' => '80',
                'enabled' => true,
                'title' => 'Compliance & Exposure',
                'status' => 'available',
                'icon' => 'phosphor-shield-chevron-duotone',
                'url' => '/sosTool/[vid]/[did]/Compliance/[caseid]',
                'image' => '/storage/pages/tools/Compliance.png',
                'showInMenu' => true,
                'showInLandingPage' => true,
                'tooltip' => 'Open Compliance & Exposure Tab',
                'description' => 'CIS, DOD STIG, Docker Bench, and exposure findings assessed automatically on every sosreport upload, with remediation guidance for each failing check.',
                'type' => 'special',
            ],
            [
                'name' => 'Alerts',
                'id' => '90',
                'enabled' => true,
                'title' => 'Alerts',
                'status' => 'available',
                'icon' => 'phosphor-bell-ringing-duotone',
                'url' => '/sosTool/[vid]/[did]/Alerts/[caseid]',
                'image' => '/storage/pages/tools/Alerts.png',
                'showInMenu' => true,
                'showInLandingPage' => true,
                'tooltip' => 'Open Alerts Tab',
                'description' => 'Create alert rules (grep match, threshold breach, or reference-case diff) evaluated automatically on every new sosreport upload, with in-app, email, event-log, and Slack delivery.',
                'type' => 'special',
            ],
            [
                'name' => 'FileSearch',
                'id' => '5',
                'enabled' => true,
                'title' => 'File Search',
                'status' => 'available',
                'icon' => 'phosphor-magnifying-glass-duotone',
                'url' => '',
                'image' => '/storage/pages/tools/FileSearch.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open File Search',
                'description' => 'File find with regular expressions support to easily locate logs, config files or command outputs across a sosreport.',
                'type' => 'basic',
            ],
            [
                'name' => 'InFileSearch',
                'id' => '6',
                'enabled' => true,
                'title' => 'In File Search',
                'status' => 'available',
                'icon' => 'phosphor-magnifying-glass-plus-duotone',
                'url' => '',
                'image' => '/storage/pages/tools/InFileSearch.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open In File Search',
                'description' => 'A powerful file search tool to locate relevant entries across sosreport files and logs.',
                'type' => 'basic',
            ],
            [
                'name' => 'FileList',
                'id' => '4',
                'enabled' => true,
                'title' => 'File Lists',
                'status' => 'available',
                'icon' => 'phosphor-list-heart-duotone',
                'url' => '',
                'image' => '/storage/pages/tools/FileList.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open Filelist',
                'description' => 'File Lists let users group related files (such as logs, command outputs, and configuration files) and open the entire set with a single click. Ideal for repeatedly analyzing the same subsystems across different sosreports.',
                'type' => 'basic',
            ],
            [
                'name' => 'Bookmarks',
                'id' => '3',
                'enabled' => true,
                'title' => 'Bookmarks',
                'status' => 'available',
                'icon' => 'phosphor-bookmarks-duotone',
                'url' => '',
                'image' => '/storage/pages/tools/Bookmarks.png',
                'showInMenu' => false,
                'showInLandingPage' => true,
                'tooltip' => 'Open Bookmark',
                'description' => 'Bookmark frequently used files for one-click access, allowing users to open important logs or configurations instantly across different sos-reports.',
                'type' => 'basic',
            ],
            [
                'name' => 'Chronoview',
                'id' => '70',
                'enabled' => false,
                'title' => 'Chronoview',
                'status' => 'development',
                'icon' => 'phosphor-timer-duotone',
                'url' => '/sosTool/[vid]/[did]/Chronoview/[caseid]',
                'image' => '/storage/pages/Carousel/carrousel04.png',
                'showInMenu' => true,
                'showInLandingPage' => false,
                'tooltip' => 'Open Chromoview Tab',
                'description' => 'A log analysis tool that extracts and displays only the records within a specified date-time range, helping users focus on the exact timeframe of an incident.',
                'type' => 'special',
            ],
        ];

        if (Schema::hasTable('modules')) {
            $moduleRows = Module::query()
                ->enabled()
                ->ofType('module')
                ->whereNotNull('tool_slug')
                ->get()
                ->map(fn (Module $m) => [
                    'name' => $m->tool_slug,
                    'id' => 'module-'.$m->id,
                    'enabled' => true,
                    'title' => $m->tool_name,
                    'status' => 'available',
                    'icon' => $m->tool_icon ?? 'phosphor-package-duotone',
                    'url' => '',
                    'image' => '',
                    'showInMenu' => true,
                    'showInLandingPage' => false,
                    'tooltip' => $m->tool_name,
                    'description' => $m->description ?? '',
                ])
                ->toArray();

            $data = array_merge($data, $moduleRows);
        }

        return collect($data)->toArray();
    }
}
